@startuml

actor Client
participant searchButton
participant MainController
participant searchBar
participant Stonk
participant StockPageController
participant HttpHandler
box Rest API
participant StonkRestService
end box
participant User

Client -> searchButton : "click"
searchButton -> MainController : toStockPage()
alt NoText
MainController -> searchBar : getText()
searchBar -> MainController : ""
MainController -> Client : "Cound not find Stock"
end
searchBar -> MainController : "Stockname"
MainController -> Stonk : new Stonk(Stockname,0)
Stonk -> Stonk : getScraperInfo(Stockname,0)
Stonk -> MainController : Stonk
MainController -> StockPageController : changeScene("stockPage.fxml", Client, Stonk)
StockPageController -> HttpHandler : buyOrSellStock()
HttpHandler -> StonkRestService : buyStonks()
StonkRestService -> User : addToPortfolio(Stonk, amount)
StonkRestService -> StockPageController : "200"

@enduml